name: check
on:
  - pull_request
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/workflows/composite/diff
        name: diff
        id: diff
        with:
          subdir: ''
      - uses: actions/setup-node@v2
        with:
          node-version: 18.x
      - name: check
        if: steps.diff.outputs.diff-count > 0
        working-directory: ./
        run: | 
          npm install
          npm run check
